version: '1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'taurus'
      MYSQL_ROOT_PASSWORD: 'pass@word1'
      # Timezone
      TZ: Asia/Jakarta
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - .DB/mysql:/var/lib/mysql
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - .FZ:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
