version: '1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'taurus'
      MYSQL_ROOT_PASSWORD: 'pass@word1'
      # Timezone
      TZ: Asia/Jakarta
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - .DB/mysql:/var/lib/mysql
